/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import javax.swing.JButton;
import progra.iii.*;

/**
 *
 * @author familia
 */
public class vArmeria extends javax.swing.JFrame {
    
    Jugador jugador;
    public vArmeria() {
        initComponents();
    }
    
    public vArmeria(Jugador pJugador) {
        initComponents();
        jugador = pJugador;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnComprarMisil = new javax.swing.JButton();
        btnComprarMultiShot = new javax.swing.JButton();
        btnComprarBomba = new javax.swing.JButton();
        btnComprarComboShot = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnComprarNave = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnComprarMisil.setText("Misil");
        btnComprarMisil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarMisilActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprarMisil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, -1));

        btnComprarMultiShot.setText("Multi-Shot");
        btnComprarMultiShot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarMultiShotActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprarMultiShot, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 100, -1));

        btnComprarBomba.setText("Bomba");
        btnComprarBomba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarBombaActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprarBomba, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 100, -1));

        btnComprarComboShot.setText("Combo-Shot");
        btnComprarComboShot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarComboShotActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprarComboShot, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 100, -1));

        jLabel1.setFont(new java.awt.Font("OCR A Std", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("500 Kg");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("OCR A Std", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("1000 Kg");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("OCR A Std", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("2000 Kg");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 266, -1, -1));

        btnComprarNave.setText("Nave Espia");
        btnComprarNave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarNaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprarNave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 100, -1));

        jLabel6.setFont(new java.awt.Font("OCR A Std", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("5000 Kg");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("OCR A Std", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("2500 Kg");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoInicio.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarMultiShotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarMultiShotActionPerformed
        if (this.jugador.getKgAcero() >= 1000){
            MultiShot multishot = new MultiShot(this.jugador);
            jugador.getArmas().add(multishot);
            jugador.setKgAcero(jugador.getKgAcero()-1000);
        }
    }//GEN-LAST:event_btnComprarMultiShotActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnComprarMisilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarMisilActionPerformed
        if (this.jugador.getKgAcero() >= 500){
            Misil misil = new Misil(this.jugador);
            jugador.getArmas().add(misil);
            jugador.setKgAcero(jugador.getKgAcero()-500);
        }
    }//GEN-LAST:event_btnComprarMisilActionPerformed

    private void btnComprarBombaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarBombaActionPerformed
        if (this.jugador.getKgAcero() >= 2000){
            Bomba bomba = new Bomba(this.jugador);
            jugador.getArmas().add(bomba);
            jugador.setKgAcero(jugador.getKgAcero()-2000);
        }
    }//GEN-LAST:event_btnComprarBombaActionPerformed

    private void btnComprarComboShotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarComboShotActionPerformed
        if (this.jugador.getKgAcero() >= 5000){
            ComboShot comboShot = new ComboShot(this.jugador);
            jugador.getArmas().add(comboShot);
            jugador.setKgAcero(jugador.getKgAcero()-5000);
        }
    }//GEN-LAST:event_btnComprarComboShotActionPerformed

    private void btnComprarNaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarNaveActionPerformed
            this.jugador.agregarNaveEspia();
    }//GEN-LAST:event_btnComprarNaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vArmeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vArmeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vArmeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vArmeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vArmeria().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprarBomba;
    private javax.swing.JButton btnComprarComboShot;
    private javax.swing.JButton btnComprarMisil;
    private javax.swing.JButton btnComprarMultiShot;
    private javax.swing.JButton btnComprarNave;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnComprarMisil(){
        return btnComprarMisil;
    }
    public JButton getBtnComprarBomba(){
        return btnComprarBomba;
    }
    public JButton getBtnComprarComboShot(){
        return btnComprarComboShot;
    }
    public JButton getBtnComprarMultiShot(){
        return btnComprarMultiShot;
    }
}
